<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <PackageId>FluentHttpClient</PackageId>
    <Description>Fluent extensions for HttpClient.</Description>
    <PackageTags>fluent httpclient rest http api web client</PackageTags>
    <Authors>Scott Offen</Authors>
    <Copyright>© 2021 - $([System.DateTime]::UtcNow.Year) Scott Offen</Copyright>
    <RepositoryUrl>https://github.com/scottoffen/fluenthttpclient</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://scottoffen.github.io/fluenthttpclient/</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>    
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>false</PublishAot>
    <TrimMode>link</TrimMode>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)FluentHttpClient.snk</AssemblyOriginatorKeyFile>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
    <FluentHttpClientPublicKey>00240000048000009400000006020000002400005253413100040000010001003529f6562b04e45eb2f0c5df9d537dc24bff64b0c93050d27ae557ef88f83e55f7857455ba6aa2cc2a9c2cd72d57e5bcbe96d3658c81de7d4d904eff0846eec0ba7973b88fdbc1b934faecdb6e69d56be4c0d0c7919a8b0c1a80107aa567c97106f84cc6e0ca7838799c57ec6e21e6a41dc5b413035c53499b1c53b1728f81a2</FluentHttpClientPublicKey>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>fluenthttpclient.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <EnablePackageValidation>true</EnablePackageValidation>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>    
    <GitVersionBaseDirectory>$(MSBuildThisFileDirectory)</GitVersionBaseDirectory>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FluentHttpClient.Tests, PublicKey=$(FluentHttpClientPublicKey)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" Condition="!Exists('packages.config')">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Label="AssemblyAttributes">
    <AssemblyAttribute Include="System.Runtime.InteropServices.ComVisibleAttribute">
      <_Parameter1>false</_Parameter1>
      <_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Text.Json" Version="[4.6.0,)" PrivateAssets="All" />
    <PackageReference Include="System.Text.Encodings.Web" Version="[4.7.2,)" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="System.Text.Json" Version="[6.0.10,)" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\fluenthttpclient.png" Pack="true" PackagePath="\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="FluentHttpClient.snk" />
  </ItemGroup>

</Project>